### ISSUE TITLE
A little tutorial?

### ISSUE THREAD

**Issue by Ymir-sh** [xtruan/FlipBIP#11]
Hello thank you for your helpful app i was just searching for something like this for the flipper but unfortunately am not familiar with hardware wallets so if you could explain to me how it works. And also is it possible to add MATIC wallet?

**Comment by xtruan** [comment]
This is a good primer on what a hardware wallet is: https://www.kraken.com/learn/what-is-crypto-hardware-wallet

I will look at MATIC, but I'm not sure if the crypto libraries I use support it.

**Comment by Ymir-sh** [comment]
Hmm ok thanks but its saying that i need to connect the device to internet
to move funds how do i do that with the flipper?

**Comment by xtruan** [comment]
That functionality is not supported at the moment (and may not be possible because of memory limitations).
