### ISSUE TITLE
Does the app support Txn creation, broadcast and signing?

### ISSUE THREAD

**Issue by xrviv** [xtruan/FlipBIP#26]
In short, can it send Bitcoins? If yes, does it reflect and allow the user to confirm the receiving address via the flipper Zero's display?

thanks!

**Comment by xtruan** [comment]
Currently no. The app is more along the lines of a "wallet creation and backup tool" than a true hardware wallet that supports transactions.

**Comment by xrviv** [comment]
Thank you for that information
