### ISSUE TITLE
installing problem

### ISSUE THREAD

**Issue by MGBH420** [xtruan/FlipBIP#29]
Hello, 
I'm having problems installing this application on my zero pinball machine. I'm on a Mac, so maybe that's why your basic instructions aren't working.
Do you have more details?
thanks in advance!

**Comment by xtruan** [comment]
I would recommend trying to install this very basic app and see if you get the same issue: https://github.com/leedave/flipper-zero-fap-boilerplate.

If this app also fails, I'd suggest reaching out on the Flipper Discord for help with your environment setup: https://discord.com/invite/flipper
