### ISSUE TITLE
Please get app working with most recent Official Flipper firmware

### ISSUE THREAD

**Issue by Skyfiles24** [xtruan/FlipBIP#36]
I used to use this app all the time but since I updated to the most recent Official firmware it is completely unusable. Please fix this and fix it asap if at all possible, it's a really great app honestly and I need it back in my life please

**Comment by xtruan** [comment]
I'll look into this, I think I just need to update the catalog entry. In the meantime, I recommend using [Momentum](https://github.com/Next-Flip/Momentum-Firmware) which bundles the app.

**Comment by xtruan** [comment]
Pending PR: https://github.com/flipperdevices/flipper-application-catalog/pull/501
