### ISSUE TITLE
Monero

### ISSUE THREAD

**Issue by TQMatvey** [xtruan/FlipBIP#6]
is it possible to add monero in future?

**Comment by TQMatvey** [comment]
also, when generating any wallet, why does it make 5 Receive Addresses?

i dont know A lot about crypto but have used it a bit :>

**Comment by TQMatvey** [comment]
also a nice idea would be to generate qr codes for addresses

**Comment by xtruan** [comment]
Monero is probably the next coin I'm most interested in adding! It does things a bit differently on the back end as far as I know so there might be some memory issues adding it.

The multiple receive addresses are a feature of BIP44 wallets. All the addresses point to the same account, but it is recommended to not reuse the same address for all transactions to make them harder to track on the blockchain.

I've also thought about QR codes. If there is enough memory, it might also be possible! Would definitely make day-to-day use of the wallet easier!

**Comment by TQMatvey** [comment]
Hm, I am aware that flipper barely has any memory, maybe it is possible to use sdcard and make some kind of swap on it? Will be quite slow but that may at least work

QRCode is probably the best feature as typing all the addresses manually kinda sucks)

**Comment by xtruan** [comment]
Yeah agreed. I think I have a solution for the QR code. I'm going to generate files that are compatible with this app: https://github.com/bmatcuk/flipperzero-qrcode

So basically you will generate a wallet and be able to open up the addresses in this other app.

Long term I might try and fully integrate it, but that will take a bit longer.

**Comment by xtruan** [comment]
> also a nice idea would be to generate qr codes for addresses

Hey, I added QR Code generation for receive addresses. It does require the third-party QR Code app as I'm just generating files that are compatible with that.

**Comment by vdo** [comment]
Looking forward to this
